#!/usr/bin/env bash
# Example of running mustache with data source from stdin.
# NOTE: This script is used as part of the mustache-cli unit tests.
cd "${0%/*}"
../mustache.go template.mustache < data-source.json
