#!/usr/bin/env bash
# Example of running mustache with a YAML data source.
# NOTE: This script is used as part of the mustache-cli unit tests.
cd "${0%/*}"
../mustache.go data-source.yaml template.mustache
